name = input("What is your name sir\Ma'am \n>")
print("Hello " + name + " here's our menu.")
print(" Coffee\n Burger\n Pizza\n Noodles" )
order = input(name + " would you like to order \n >")
print("Thanks!! for ordering "+ name +" your order " + order + " will be ready soon!")
